@url_dev = http://localhost:3002

POST {{url_dev}}/v1/api/shop/logout
Content-Type: application/json
x-api-key: 14e13051b-8fe9-4146-beb6-b08449d1cfd923
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzk1YjQ2Zjk0MmM1NmFmZWI2M2Q0ZDEiLCJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc4NjQzMzgsImV4cCI6MTczODAzNzEzOH0.KwjfB3jD4idoYEg1uBb9p0J7jIBfXRVDD6CLbqzKAjKUy67rRuz0dA51j-bldUTAo7XmRiOKbeFgVS5atwvJ603TafWqf7kA_tijz1nB6oFtu-vFFQ4qNWjvKTV9euOdhL7MJXM3NDonpSepxS5i7F9Jq23uiw9Y-3YLHs1u6tlRT-pYhTsguFxtLpvZ81f3jpwBBlkYnnI0yc-FDcscTbuMjycq5id1aC6mgga44iKnXDj7FPq43sjsdRSnUM2YFacCziHd7uRPtnI5Dym708h3L2zdAJUg0WR4EBxiFNsLqy1T6qTs2Am6wgBPbGJmLJyxCwzSdmAWTQV7A0zmyg
x-client-id: 6795b46f942c56afeb63d4d1
