@url_dev = http://localhost:3002

POST {{url_dev}}/v1/api/shop/refresh-token
Content-Type: application/json
x-api-key: 123
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzk1YjQ2Zjk0MmM1NmFmZWI2M2Q0ZDEiLCJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc4Njg2MjMsImV4cCI6MTczODA0MTQyM30.CkSNlNHbacmP_XymU_VCywNQZhsnEqogsL_-9ccPd9Doe4s12M5bllxiMngCGfH6RtWdwgwEMyTM_5vE9vmCzAFYJLAhyF3xQWErUopWJPmOThguAIuP2m2I7qTDVMRvNOujtL7ia1P_9FX7kb3dD95P7vYJtqxfPI7m-b186rXdPb27wSNwYwNKRWqA2R-uhNIfdf4xQlQ6ajfwyJOOu3ZtQ49kM3sJzXoDCdeKR6PPI09Y2w9ZuymaQq2Bp3nsk7KKtqmJnZbCjx4zU0NB9ckvuSTDiBL9IkyjrzQpmPHgXyPiR1p_9RT1lQk_QjZ1Z8lawYPsb6EP7hLjIuE9cg
x-client-id: 6795b46f942c56afeb63d4d1

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzk1YjQ2Zjk0MmM1NmFmZWI2M2Q0ZDEiLCJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc4Njg2MjMsImV4cCI6MTczODQ3MzQyM30.Oow5Q0iiZxFahohQDA_VVvRTPtLOBZ926kTkn4bSNFOjGcm5n5c13BfDg3Wfs2IPg82bFl2okG5bRz46vbLuNQVoP2IWL3YuFpymy9r8WoVHUrXsEc06Xt0DyKV4ONcULLwfuDLKsPp1F_ZIGbNAYNTlKVpXvuYTQJmpE5xsXHzo_AflhYWowxY7NdKzs4MGvCIf1b9R8tE7IV1JeqKUd2kieT5TRAojDmH9_L1RzHB9uHSz4LL1gWgxqdHURrHmXHLvk1vLXeLLmdoaQtDSHaU9OsXSdnZw5tKZfnKU0wGFpXtzs-yBOk1FLuLLSCIpZh-r1UWtNQansLZlgJJqLA"
}